# Site settings
baseURL = "https://kostis-portfolio.netlify.app/"
languageCode = "en-us"
title = "Portfolio website for Tong Wu"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Tong Wu"
  description = "As a Master of Financial Analysis student at London Business school, I prefer to enter into the investment banking in the future. Accumulating various internship experiences in the capital markets, I am confident that I would be a good fit for the position based on the following transferrable skills: Analytical and Modelling Skills: During my 4-year undergraduate study, I’ve laid a solid foundation in the field of finance and accounting. Moreover, when I was engaged in the C-round investment project at CITIC Capital, I leveraged my technical skillsets to build the operation models and conducted company valuation using Relative Valuation Method. Communication and Collaboration Skills: As an Investment Banking Intern at CICC, I was staffed on the Due Diligence of 3 different projects. With my excellent teamwork and multi-tasking abilities, I maintained a transparent communication with supervisors and colleagues throughout the whole process, which greatly improved the working efficiency.Research and Quick-learning Skills: Once I was asked to write a report on a certain field, about which I lacked relevant knowledge. Therefore, I firstly collected public information via diversified databases, and actively consulted my alumni and professors, who possessed industry expertise. Ultimately, I delivered the report punctually and got approval."

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Tong Wu"
    subtitle = "Portfolio website"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "Blogs"
      url = "blogs"

#    [[params.navigation.links]]
#      name = "Generic Blog"
#      url = "blogs/ipsum"

#    [[params.navigation.links]]
#      name = "Elements"
#      url = "elements.html"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
      name = "My projects"
      url = "blogs"

    # Button Style 2
#    [[params.navigation.button2]]
#      name = "Log In"
#      url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Hi, my name is Tong Wu"
    subtitle = "My portfolio website \n RELEASED UNDER THE CREATIVE COMMONS."
    buttonText = "Get Started"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.

    [[params.tiles.showcase]]
      title = "Donald Trump"
      subtitle = "Make America Great Again"
      image = "pic99.jpeg"
      url = "/blogs/trump"    


    [[params.tiles.showcase]]
      title = "Biden"
      subtitle = "Biden says he will seek consensus on tax plan"
      image = "pic11.jpg"
      url = "blogs/biden"

    [[params.tiles.showcase]]
      title = "Barack Obama"
      subtitle = "44th President of the United States"
      image = "pic03.jpg"
      url = "blogs/obama"

    [[params.tiles.showcase]]
      title = "Hillary Clinton"
      subtitle = "American politician"
      image = "pic04.jpg"
      url = "blogs/hillary"

#    [[params.tiles.showcase]]
#      title = "Consequat"
#      subtitle = "Ipsum Dolor Sit Amet"
#      image = "pic05.jpg"
#      url = "blogs/ipsum"

#    [[params.tiles.showcase]]
#      title = "Etiam"
#      subtitle = "Feugiat Amet Tempus"
#      image = "pic06.jpg"
#      url = "blogs/ipsum"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
#  [params.two]
#    enable = true
#    title = "Massa libero"
#    subtitle = """Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero. 
#    Mauris aliquet magna magna sed nunc rhoncus pharetra. 
#    Pellentesque condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia pellentesque lorem ipsum dolor. 
#    Nullam et orci eu lorem consequat tincidunt. Vivamus et sagittis libero.
#    Mauris aliquet magna magna sed nunc rhoncus amet pharetra et feugiat tempus."""
#    buttonText = "Get Started"
#    url = "blogs"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    formEmail = "twu.mfa2021@london.edu"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "twu.mfa2021@london.edu"

    [[params.contact.phone]]
    title = "Phone"
    phone = "(+86)15012592592"

    [[params.contact.address]]
    title = "Address"
    street = "Street"
    city = "London 00000"
    country = "British"

  # Footer section
  [params.footer]
    enable = true
#    copyright = "Company Name"

# Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com/SteveWu1997"

#     [[params.footer.social]]
#      icon = "fa-linkedin"
#      url= "https://www.linkedin.com/in/kostis-christodoulou-285147/"
#      label = "LinkedIn"

#    [[params.footer.social]]
#      icon = "fa-instagram"
#      url= "https://www.instagram.com/kostisc"
#      label = "Instagram"
 
#    [[params.footer.social]]
#      icon = "fa-twitter"
#      url= "https://www.twitter.com/kostisc"
#      label = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com/SteveWu"
      label = "Steve Wu"

#        [[params.footer.quicklinks]]
#      text = "Design: "
#      url= "https://www.html5up.net"
#      alt = "HTML5 UP"